baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Muistola"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[menu]
    [[menu.main]]
        identifier = "etusivu"
        name = "Etusivu"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "palvelut"
        name = "Palvelut"
        url = "/palvelut/"
        weight = 2
        [[menu.main]]
            name = "Päivätoiminta"
            parent = "palvelut"
            identifier = "kuntouttava"
            url = "/palvelut/#1"
            weight = 1
        [[menu.main]]
            name = "Perhehoito"
            parent = "palvelut"
            identifier = "perhehoito"
            url = "/palvelut/#2"
            weight = 2
        [[menu.main]]
            name = "Pesupalvelu"
            parent = "palvelut"
            identifier = "pyykkipalvelu"
            url = "/palvelut/#3"
            weight = 3
        [[menu.main]]
            name = "Toimintakyvyn arviointi"
            parent = "palvelut"
            identifier = "arviointi"
            url = "/palvelut/#4"
            weight = 4
        [[menu.main]]
            name = "Palvelumaksut"
            parent = "palvelut"
            identifier = "palvelumaksut"
            url = "/palvelut/#5"
            weight = 5
    [[menu.main]]
        identifier = "tietoa"
        name = "Tietoa meistä"
        url = "/tietoa-muistolasta/"
        weight = 3
        [[menu.main]]
            name = "Tilat"
            parent = "tietoa"
            identifier = "tilat"
            url = "/tietoa-muistolasta/#1"
            weight = 1
        [[menu.main]]
            name = "Vastuuhenkilö"
            parent = "tietoa"
            identifier = "vastuuhenkilö"
            url = "/tietoa-muistolasta/#2"
            weight = 2
        [[menu.main]]
            name = "Toimintaperiaate"
            parent = "tietoa"
            identifier = "toimintaperiaate"
            url = "/tietoa-muistolasta/#3"
            weight = 3
        [[menu.main]]
            name = "Arvot"
            parent = "tietoa"
            identifier = "arvot"
            url = "/tietoa-muistolasta/#4"
            weight = 4
        [[menu.main]]
            name = "Historia"
            parent = "tietoa"
            identifier = "historia"
            url = "/tietoa-muistolasta/#5"
            weight = 5
    [[menu.main]]
        identifier = "yhteystiedot"
        name = "Yhteystiedot"
        url = "/yhteystiedot/"
        weight = 4
